{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "346ed91a-7df2-4c1c-b5a2-b4a342bfc23a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import streamlit as st\n",
    "from sklearn.utils import shuffle\n",
    "\n",
    "# -------------------------------\n",
    "# Load & clean data\n",
    "# -------------------------------\n",
    "df = pd.read_csv(\"zomato_dataset_refined.csv\")\n",
    "\n",
    "# Remove unwanted column if present\n",
    "if \"Unnamed: 0\" in df.columns:\n",
    "    df = df.drop(\"Unnamed: 0\", axis=1)\n",
    "\n",
    "# Remove extra spaces from column names\n",
    "df.columns = df.columns.str.strip()\n",
    "\n",
    "# -------------------------------\n",
    "# Recommendation functions\n",
    "# -------------------------------\n",
    "def rate_recom(data, price):\n",
    "    data = data[data[\"Prices\"] <= price]\n",
    "    data = shuffle(data)\n",
    "    return data.drop(\n",
    "        [\"Dining Rating\", \"Delivery Rating\",\n",
    "         \"Dining Votes\", \"Delivery Votes\",\n",
    "         \"Place Name\", \"City\", \"Special mentions\"],\n",
    "        axis=1\n",
    "    )\n",
    "\n",
    "def dine_recom(data, rating):\n",
    "    data = data[data[\"Dining Rating\"] == rating]\n",
    "    data = shuffle(data)\n",
    "    return data.drop(\n",
    "        [\"Dining Rating\", \"Delivery Rating\",\n",
    "         \"Dining Votes\", \"Delivery Votes\",\n",
    "         \"Place Name\", \"City\", \"Special mentions\"],\n",
    "        axis=1\n",
    "    )\n",
    "\n",
    "def del_recom(data, rating):\n",
    "    data = data[data[\"Delivery Rating\"] == rating]\n",
    "    data = shuffle(data)\n",
    "    return data.drop(\n",
    "        [\"Dining Rating\",\n",
    "         \"Dining Votes\", \"Delivery Votes\",\n",
    "         \"Place Name\", \"City\", \"Special mentions\"],\n",
    "        axis=1\n",
    "    )\n",
    "\n",
    "# -------------------------------\n",
    "# Streamlit UI\n",
    "# -------------------------------\n",
    "st.title(\"🍽️ Cuisine Recommender System\")\n",
    "st.write(\"Cuisine recommendations based on Zomato data\")\n",
    "\n",
    "st.sidebar.title(\"Filters\")\n",
    "st.sidebar.text(\"Developed by Niharika Velugu\")\n",
    "\n",
    "# -------------------------------\n",
    "# City selection\n",
    "# -------------------------------\n",
    "city = st.selectbox(\n",
    "    \"Select Your City:\",\n",
    "    sorted(df[\"City\"].dropna().unique())\n",
    ")\n",
    "\n",
    "df_city = df[df[\"City\"] == city]\n",
    "\n",
    "# -------------------------------\n",
    "# Place selection\n",
    "# -------------------------------\n",
    "place = st.selectbox(\n",
    "    \"Select Place Name:\",\n",
    "    sorted(df_city[\"Place Name\"].dropna().unique())\n",
    ")\n",
    "\n",
    "df_place = df_city[df_city[\"Place Name\"] == place]\n",
    "\n",
    "# -------------------------------\n",
    "# Cuisine selection\n",
    "# -------------------------------\n",
    "cuisine = st.selectbox(\n",
    "    \"Select Cuisine:\",\n",
    "    sorted(df_place[\"Cuisine\"].dropna().unique())\n",
    ")\n",
    "\n",
    "df_cuisine = df_place[df_place[\"Cuisine\"] == cuisine]\n",
    "\n",
    "# -------------------------------\n",
    "# Special mentions\n",
    "# -------------------------------\n",
    "special = st.selectbox(\n",
    "    \"Special Mentions:\",\n",
    "    sorted(df_cuisine[\"Special mentions\"].dropna().unique())\n",
    ")\n",
    "\n",
    "df_final = df_cuisine[df_cuisine[\"Special mentions\"] == special]\n",
    "\n",
    "# -------------------------------\n",
    "# Recommendation logic\n",
    "# -------------------------------\n",
    "if not df_final.empty:\n",
    "    price_limit = df_final[\"Prices\"].quantile(0.40)\n",
    "    best_dine = df_final[\"Dining Rating\"].max()\n",
    "    best_delivery = df_final[\"Delivery Rating\"].max()\n",
    "\n",
    "    if st.button(\"Recommend\"):\n",
    "        st.subheader(\"💰 Best on Price\")\n",
    "        st.table(rate_recom(df_final, price_limit).head(5))\n",
    "\n",
    "        st.subheader(\"🍽️ Best Dining Rating\")\n",
    "        st.table(dine_recom(df_final, best_dine).head(5))\n",
    "\n",
    "        st.subheader(\"🚀 Fast Delivery\")\n",
    "        st.table(del_recom(df_final, best_delivery).head(5))\n",
    "else:\n",
    "    st.warning(\"No data available for the selected filters.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.14"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
